# Generated by Django 4.2.10 on 2024-03-06 13:04

import WorldOfSpeedApp.profiles.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=WorldOfSpeedApp.profiles.models.CustomURLField(blank=True, null=True),
        ),
    ]
