# Generated by Django 4.2.10 on 2024-03-05 13:21

import WorldOfSpeedApp.cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=WorldOfSpeedApp.cars.models.UniqueURLField(error_messages={'unique': 'This image URL is already in use! Provide a new one.'}, unique=True),
        ),
    ]
