# Generated by Django 4.2.10 on 2024-03-06 13:13

import WorldOfSpeedApp.profiles.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_car_model_alter_car_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=WorldOfSpeedApp.profiles.models.CustomURLField(error_messages={'unique': 'This image URL is already in use! Provide a new one.'}, unique=True),
        ),
    ]
